ci: testing

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -6,19 +6,35 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/joinself/android-build:latest
     steps:
       - name: Setup job
         uses: joinself/github-actions-public/setup-job@main
       - name: Build
         shell: bash
+        env:
+          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
         run: |
           . ${GITHUB_WORKSPACE}/.ci/env
-          cd android/SelfDemo
-          ./gradlew :app:assembleDebug
+
+          workflow="self-sdk-examples:android-build"
+          id=$(date | md5sum | head -c 8)
+          gh workflow run ${workflow} -R joinself/github-workflows-dispatch -r main -f id=${id} -f git-ref=${CI_REF_NAME}
+
+          echo "Calling remote workflow: ${workflow} (${id})"
+          for ((i = 0; i < 30; i++)); do
+            echo "Waiting for workflow to complete..."
+            status=$(gh run list -R joinself/github-workflows-dispatch --json name,databaseId,conclusion --jq ".[] | select(.name==\"${workflow} - ${id}\") | (.databaseId|tostring) + \":\" + .conclusion")
+            dispatch_run_id="${status%:*}"
+            conclusion="${status#*:}"
+            [[ "${conclusion}" == "success" ]] && echo "Workflow complete" && break
+            [[ "${conclusion}" == "failure" ]] && echo "Workflow failed" && exit 1
+            [[ "${i}" == "29" ]] && echo "Workflow timeout" && exit 1
+            sleep 10
+          done
+
+          echo "${dispatch_run_id}" > ${CI_WORKDIR}/.ci/dispatch-run-id
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
           name: build-artifacts
-          path: android/SelfDemo/app/build/outputs/apk/debug/self-demo-debug.apk
+          path: .ci/dispatch-run-id
