ci: testing

diff --git a/.github/workflows/android-publish.yml b/.github/workflows/android-publish.yml
--- a/.github/workflows/android-publish.yml
+++ b/.github/workflows/android-publish.yml
@@ -17,14 +17,15 @@ jobs:
           . ${GITHUB_WORKSPACE}/.ci/env
 
           id=$(date | md5sum | head -c 8)
-          gh workflow run remote-trigger -R joinself/github-workflows-dispatch -r main -f id=${id} -f run-id=${CI_RUN_ID}
+          gh workflow run self-sdk-examples:android-publish -R joinself/github-workflows-dispatch -r main -f id=${id} -f run-id=${CI_RUN_ID}
 
           for ((i = 0; i < 30; i++)); do
             echo "Waiting for remote workflow..."
-            conclusion=$(gh run list -R joinself/github-workflows-dispatch -w self-sdk-examples.yml --json name,conclusion --jq ".[] | select(.name==\"remote-trigger - ${id}\") | .conclusion")
+            conclusion=$(gh run list -R joinself/github-workflows-dispatch --json name,conclusion --jq ".[] | select(.name==\"self-sdk-examples:android-publish - ${id}\") | .conclusion")
+            #conclusion=$(gh run list -R joinself/github-workflows-dispatch -w self-sdk-examples:android-publish.yml --json name,conclusion --jq ".[] | select(.name==\"self-sdk-examples:android-publish - ${id}\") | .conclusion")
             #conclusion=$(gh run list -R joinself/github-workflows-dispatch -e workflow_dispatch -w self-sdk-examples.yml --json name,conclusion | jq -r --arg ID "update-apps - ${id}" '.[] | select(.name==$ID) | .conclusion')
             [[ "${conclusion}" == "success" ]] && echo "Deployment complete" && exit 0
-            [[ "${conclusion}" == "failure" ]] && echo "Deployment failed" && exit 0
+            [[ "${conclusion}" == "failure" ]] && echo "Deployment failed" && exit 1
             [[ "${i}" == "29" ]] && echo "Deployment timeout" && exit 1
             sleep 10
           done
