ci: android workflow fixes (#43)

diff --git a/.github/workflows/android-publish.yml b/.github/workflows/android-publish.yml
--- a/.github/workflows/android-publish.yml
+++ b/.github/workflows/android-publish.yml
@@ -16,19 +16,16 @@ jobs:
         run: |
           . ${GITHUB_WORKSPACE}/.ci/env
 
-          exit 0
-
+          workflow="self-sdk-examples:android-publish"
           id=$(date | md5sum | head -c 8)
-          gh workflow run remote-trigger -R joinself/github-workflows-dispatch -r main -f id=${id} -f foo=bar
+          gh workflow run ${workflow} -R joinself/github-workflows-dispatch -r main -f id=${id} -f run-id=${CI_RUN_ID}
 
+          echo "Calling remote workflow: ${workflow} (${id})"
           for ((i = 0; i < 30; i++)); do
-            echo "Waiting for remote workflow..."
-            conclusion=$(gh run list -R joinself/github-workflows-dispatch -w self-sdk-examples.yml --json name,conclusion --jq ".[] | select(.name==\"remote-trigger - ${id}\") | .conclusion")
-            #conclusion=$(gh run list -R joinself/github-workflows-dispatch -e workflow_dispatch -w self-sdk-examples.yml --json name,conclusion | jq -r --arg ID "update-apps - ${id}" '.[] | select(.name==$ID) | .conclusion')
-            [[ "${conclusion}" == "success" ]] && echo "Deployment complete" && exit 0
-            [[ "${conclusion}" == "failure" ]] && echo "Deployment failed" && exit 0
-            [[ "${i}" == "29" ]] && echo "Deployment timeout" && exit 1
+            echo "Waiting for workflow to complete..."
+            conclusion=$(gh run list -R joinself/github-workflows-dispatch --json name,conclusion --jq ".[] | select(.name==\"${workflow} - ${id}\") | .conclusion")
+            [[ "${conclusion}" == "success" ]] && echo "Workflow complete" && exit 0
+            [[ "${conclusion}" == "failure" ]] && echo "Workflow failed" && exit 1
+            [[ "${i}" == "29" ]] && echo "Workflow timeout" && exit 1
             sleep 10
           done
-
-          exit 0
