ci android release bundle (#50)

diff --git a/.github/workflows/ci-android.yml b/.github/workflows/ci-android.yml
--- a/.github/workflows/ci-android.yml
+++ b/.github/workflows/ci-android.yml
@@ -11,11 +11,29 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    uses: ./.github/workflows/android-build.yml
-    secrets: inherit
-  publish:
-    if: ${{ github.ref == 'refs/heads/main' }}
-    uses: ./.github/workflows/android-publish.yml
-    secrets: inherit
-    needs: build
+  ci:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup job
+        uses: joinself/github-actions-public/setup-job@main
+      - name: CI
+        shell: bash
+        env:
+          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
+        run: |
+          . ${GITHUB_WORKSPACE}/.ci/env
+
+          workflow="CI - Android"
+          id=$(date | md5sum | head -c 8)
+          gh workflow run "${workflow}" -R joinself/self-sdk-examples-gha -r main -f id=${id} -f git-ref=${CI_REF_NAME}
+
+          echo "Calling remote workflow: ${workflow} (${id})"
+          for ((i = 0; i < 120; i++)); do
+            echo "Waiting for workflow to complete..."
+            conclusion=$(gh run list -R joinself/self-sdk-examples-gha --json name,conclusion --jq ".[] | select(.name==\"${workflow} (${id})\") | .conclusion")
+            echo "conclusion: ${conclusion}"
+            [[ "${conclusion}" == "success" ]] && echo "Workflow complete" && break
+            [[ "${conclusion}" == "failure" ]] && echo "Workflow failed" && exit 1
+            [[ "${i}" == "119" ]] && echo "Workflow timeout" && exit 1
+            sleep 15
+          done
